name: Build and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build application
        run: go build -o myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-built-application
          path: myapp
          retention-days: 7  # The artifact will be stored for 7 days
          
