name: Transfer Extension

on:
  workflow_dispatch:

jobs:
  transfer_extension:
    # runs-on: [self-hosted, linux, osp-cloud-devOps-runner1]
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Run ID
        id: get_run_id
        run: |
          REPO="dozman99/test" # Replace with your target repository
          WORKFLOW_ID="blank.yml" # Replace with the target workflow file name
          GH_TOKEN="${{ secrets.GH_TOKEN }}"
          
          RUN_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW_ID" | jq '.id')
          
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: empty_artifact.txt 
          github-token: ${{ secrets.GH_TOKEN }}
          repository: dozman99/test 
          run-id: ${{ env.RUN_ID }}
          
